# Site settings
title: Turtles All The Way Down
email: brkscllns@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Systems/Devops Engineer from Portland, OR.
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "http://terrapinstation.github.io" # the base hostname & protocol for your site
twitter_username: terrapinst8n
github_username:  terrapinstation

# Build settings
markdown: kramdown
permalink: /:year/:title:output_ext

# Default settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: true